### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by min0me** [rafachurre/IoTMyAdmin#1]
Hello,
Just checking if this project has been abandoned..

**Comment by rlopmar** [comment]
Hi,

Yes somehow this prototype was abandoned. I am trying to find time to build
a new solution, with the same goal, but based on Angular + Express + Node +
Firebase, using webSockets instead of HTTP calls.

Thank you,
Rafael

**Comment by min0me** [comment]
Thank you for the update.
Thats a shame, as it ticked all the right boxes, but interested to see how the new solution develops

**Comment by rlopmar** [comment]
if you are looking for something similar, and completely Open Source... take a look at [Kaa Project](http://kaaproject.github.io/kaa)

**Comment by min0me** [comment]
Thank you for the suggestion. Its one i have seen. I am after something that i can run over a standard web hosting. Everything (other then yours) requires something custom that can only be had on a VPS. Going for a service has costs, data ownership issues, over complications and other implications associated with it.

Thanks anyways

**Comment by rlopmar** [comment]
Then you can use mine... It is stable enough for logging.... Not many
functionality for rendering data and no two-way communication. Only device
to server, but for many tasks, is enuogh
